name = "AdvRBMs"
uuid = "5c8d321f-d88f-4112-b4bc-67901fc2de0a"
authors = ["Jorge Fernandez-de-Cossio-Diaz <j.cossio.diaz@gmail.com>"]
version = "2.0.0-DEV"

[deps]
FillArrays = "1a297f60-69ca-5386-bcde-b61e274b549b"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Optimisers = "3bd65402-5787-11e9-1adc-39752487f4e2"
RestrictedBoltzmannMachines = "12e6b396-7db5-4506-8cb6-664a4fe1e50e"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"

[compat]
FillArrays = "0.13, 1"
LinearAlgebra = "1.8"
Optimisers = "0.2, 0.3, 0.4"
RestrictedBoltzmannMachines = "3.8"
Statistics = "1.8"
julia = "1.8"
